name: ci

env:
  CTEST_PARALLLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  static-fortran:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fc: gfortran
            cmd: sudo apt update && sudo apt install liblapack-dev libopenmpi-dev openmpi-bin
          - os: macos-latest
            fc: gfortran-11
            cmd: brew install lapack open-mpi

    runs-on: ${{ matrix.os }}
    timeout-minutes: 7

    steps:

    - uses: actions/checkout@v2

    - name: install prereqs
      run: ${{ matrix.cmd }}

    - name: Config static
      run: cmake -B build -Darith=d -DBUILD_SHARED_LIBS:BOOL=off
      env:
        FC: ${{ matrix.fc }}

    - run: cmake --build build --parallel

    - run: ctest --test-dir build --preset default -V


  shared-fortran:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fc: gfortran
            cmd: sudo apt update && sudo apt install liblapack-dev libopenmpi-dev openmpi-bin
          - os: macos-latest
            fc: gfortran-11
            cmd: brew install lapack open-mpi

    runs-on: ${{ matrix.os }}
    timeout-minutes: 7

    steps:

    - uses: actions/checkout@v2

    - name: install prereqs
      run: ${{ matrix.cmd }}

    - name: Config shared
      run: cmake -B build -Darith=d -DBUILD_SHARED_LIBS:BOOL=on
      env:
        FC: ${{ matrix.fc }}

    - run: cmake --build build --parallel

    - run: ctest --test-dir build --preset default -V
