name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

 fortran:
    strategy:
      matrix:
        shared: [true, false]
        img: [ {os: ubuntu-latest, fc: gfortran, cmd: sudo apt update && sudo apt install liblapack-dev libopenmpi-dev openmpi-bin},
               {os: macos-latest, fc: gfortran-11, cmd: brew install lapack open-mpi}
        ]

    runs-on: ${{ matrix.img.os }}
    timeout-minutes: 7
    env:
      FC: ${{ matrix.img.fc }}

    steps:

    - name: install prereqs
      run: ${{ matrix.img.cmd }}

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.19'

    - uses: actions/checkout@v2

    - name: Config
      run: cmake -B build -Darith=d -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}

    - name: build
      run: cmake --build build --parallel

    - name: test
      run: ctest --test-dir build --preset default -V

    - name: install
      run: cmake --install build

    - name: example Config
      run: cmake -S example -B example/build -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }}

    - name: build
      run: cmake --build example/build --parallel

    - name: test
      run: ctest --test-dir example/build --preset default -V
