name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  FC: gfortran-12
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"
      - "!scripts/**"


jobs:

 fortran:
    strategy:
      matrix:
        shared: [true, false]
        img: [ {os: ubuntu-latest, cmd: sudo apt update && sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin},
               {os: macos-latest, cmd: brew install open-mpi}
        ]

    runs-on: ${{ matrix.img.os }}
    timeout-minutes: 7

    steps:

    - name: install prereqs
      run: ${{ matrix.img.cmd }}

    - uses: actions/checkout@v4

    - name: Config
      run: cmake -B build -DBUILD_SINGLE:BOOL=off -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}

    - name: build
      run: cmake --build build --parallel

    - name: test
      run: ctest --test-dir build --preset default -V

    - name: install
      run: cmake --install build

    - name: example Config
      run: cmake -S example -B example/build -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }}

    - name: build
      run: cmake --build example/build --parallel

    - name: test
      run: ctest --test-dir example/build --preset default -V
