name: ci

on: [push, pull_request]

jobs:

  linuxMeson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Meson
      run: python -m pip install meson
    - name: Install packages
      run: sudo apt install -yq --no-install-recommends ninja-build gfortran liblapack-dev libopenmpi-dev openmpi-bin
    - name: Meson configure
      run: meson setup build -Dsystem_blas=true
      env:
        FC: gfortran
    - name: Meson test
      run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macosMeson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        brew install gcc ninja open-mpi
        python -m pip install meson
    - name: Meson configure
      run: meson setup build
      env:
        FC: gfortran
    - name: Meson test
      run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt