name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin

    - run: cmake -B build -Darith=d --install-prefix=${HOME}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default

    - run: cmake --install build


  mac:
    needs: linux
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install open-mpi

    - run: cmake -B build -Darith=d
    - run: cmake --build build
    - run: ctest --test-dir build --preset default

    - run: cmake --install build
