name: ci_linux

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libopenmpi-dev openmpi-bin

    - run: cmake --preset default -Darith=d
    - run: cmake --build --preset default
    - run: ctest --preset default

    - run: cmake --install build

    - run: cmake -S EXAMPLE -B EXAMPLE/build -DSCALAPACK_ROOT=build
    - run: cmake --build EXAMPLE/build --parallel
    - run: ctest  -parallel 2 --output-on-failure
      working-directory: EXAMPLE/build
