name: ci_macos

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja open-mpi lapack

    - run: ctest -S setup.cmake -VV

  meson:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: brew install ninja open-mpi lapack
    - run: pip install meson

    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9

    - run: meson compile -C build

    - run: meson test -C build -v
