name: ci_macos

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"
  pull_request:


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install ninja open-mpi lapack

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
        CC: gcc-9


  meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install ninja open-mpi lapack
    - run: pip install meson

    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9

    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Configlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt
