name: ci_macos
env:
   HOMEBREW_NO_INSTALL_CLEANUP: 1
   CC: gcc-10
   FC: gfortran-10
   CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install open-mpi ninja

    - run: cmake --preset=build -Darith=d -DCMAKE_INSTALL_PREFIX=~/scalapack
    - run: cmake --build build --parallel
    - run: cmake --install build
    - run: ctest --output-on-failure --parallel 2
      working-directory: build

  meson:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: brew install ninja open-mpi lapack
    - run: pip install meson

    - run: meson setup build

    - run: meson compile -C build

    - run: meson test -C build -v
