name: ci_macos
env:
   HOMEBREW_NO_INSTALL_CLEANUP: 1
   CC: gcc-10
   FC: gfortran-10

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install open-mpi ninja

    - run: cmake --preset default -Darith=d
    - run: cmake --build --preset default
    - run: ctest --preset default

    - run: cmake --install build

    - run: cmake -S EXAMPLE -B EXAMPLE/build -DSCALAPACK_ROOT=~/local
    - run: cmake --build EXAMPLE/build --parallel
    - run: ctest  -parallel 2 --output-on-failure
      working-directory: EXAMPLE/build

  meson:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: brew install ninja open-mpi lapack
    - run: pip install meson

    - run: meson setup build

    - run: meson compile -C build

    - run: meson test -C build -v
